version: 1

apt:
  arch: amd64
  allow_unauthenticated: true
  sources:
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu jammy main universe'
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu jammy-updates main universe'
  packages:
    - libc6
    - libstdc++6
    - libglib2.0-0
    - libx11-6
    - libxext6
    - libxrender1
    - libxrandr2
    - libxfixes3
    - libxi6
    - libxcb1
    - zlib1g
    - libasound2
    - libpulse0
    - libdbus-1-3
    - libfreetype6
    - libfontconfig1

AppDir:
  path: ./AppDir
  app_info:
    id: org.fooyin.Fooyin
    name: Fooyin
    icon: fooyin
    version: !ENV ${VERSION}
    exec: usr/local/bin/fooyin
    exec_args: $@

  runtime:
    env:
      LD_LIBRARY_PATH: "${APPDIR}/usr/local/lib:${APPDIR}/usr/local/lib/x86_64-linux-gnu:${APPDIR}/usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}"
      QT_PLUGIN_PATH: "${APPDIR}/usr/local/lib/qt6/plugins:${APPDIR}/usr/local/lib/x86_64-linux-gnu/qt6/plugins"
      QML2_IMPORT_PATH: "${APPDIR}/usr/local/lib/qt6/qml:${APPDIR}/usr/local/lib/x86_64-linux-gnu/qt6/qml"
      QT_QPA_PLATFORM_PLUGIN_PATH: "${APPDIR}/usr/local/lib/qt6/plugins/platforms:${APPDIR}/usr/local/lib/x86_64-linux-gnu/qt6/plugins/platforms"
      PATH: "${APPDIR}/usr/local/bin:${PATH}"

  files:
    include:
      - usr/local/bin/fooyin
      - usr/local/share/applications/fooyin.desktop
      - usr/local/share/icons/hicolor/*/apps/fooyin.png

      # Qt 6.8.0 библиотеки
      - usr/local/lib/libQt6*.so.*
      - usr/local/lib/x86_64-linux-gnu/libQt6*.so.*

      # Qt плагины
      - usr/local/lib/qt6/plugins/**/*
      - usr/local/lib/x86_64-linux-gnu/qt6/plugins/**/*

      # Qt QML
      - usr/local/lib/qt6/qml/**/*
      - usr/local/lib/x86_64-linux-gnu/qt6/qml/**/*

      # FFmpeg 7.x
      - usr/local/lib/libav*.so.*
      - usr/local/lib/libsw*.so.*

      # ICU 76
      - usr/local/lib/libicu*.so.*

    exclude:
      - usr/share/doc
      - usr/share/man
      - usr/local/share/doc
      - usr/local/share/man

AppImage:
  arch: x86_64
  update-information: "gh-releases-zsync|fooyin/fooyin|latest|Fooyin-*-x86_64.AppImage.zsync"
