version: 1
AppDir:
  path: ./AppDir
  app_info:
    id: org.fooyin.Fooyin
    name: Fooyin
    icon: fooyin
    # Версия будет установлена workflow'ом через переменную окружения
    version: $VERSION
    # Путь к исполняемому файлу внутри AppDir
    # Предполагаем установку в /usr/local/bin
    exec: usr/local/bin/fooyin
    exec_args: $@
  runtime:
    env:
      # Указываем путь к нашим собранным библиотекам первым
      # $APPDIR будет заменён на путь к AppDir внутри AppImage
      LD_LIBRARY_PATH: "${APPDIR}/usr/local/lib:${APPDIR}/usr/local/lib/x86_64-linux-gnu:${APPDIR}/usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}"
      # Qt
      QT_PLUGIN_PATH: "${APPDIR}/usr/local/lib/x86_64-linux-gnu/qt6/plugins"
      QML2_IMPORT_PATH: "${APPDIR}/usr/local/lib/x86_64-linux-gnu/qt6/qml"
      QT_QPA_PLATFORM_PLUGIN_PATH: "${APPDIR}/usr/local/lib/x86_64-linux-gnu/qt6/plugins/platforms"
  # Поскольку мы используем нестандартные версии Qt и FFmpeg,
  # мы не можем устанавливать их через стандартный apt include.
  # Мы будем собирать их и устанавливать в /usr/local внутри AppDir.
  # Здесь мы исключаем стандартные версии, чтобы избежать конфликтов.
  # Мы также не включаем libicu70, так как Qt 6.8.0 будет использовать libicu76.
  apt:
    arch: amd64
    sources:
      - sourceline: 'deb http://archive.ubuntu.com/ubuntu jammy main universe'
      - sourceline: 'deb http://archive.ubuntu.com/ubuntu jammy-updates main universe'
    # Включаем только те зависимости, которые не конфликтуют
    # и необходимы для работы Fooyin или для сборки Fooyin,
    # но НЕ включаем стандартные Qt, FFmpeg и старую ICU.
    include:
      # Зависимости Fooyin (кроме Qt/FFmpeg/старой ICU)
      - libpulse0
      - libasound2
      - libtag1v5
      # libglib2.0-0
      - libglib2.0-0
      # Зависимости для сборки Fooyin (если сборка происходит здесь)
      # - build-essential
      # - cmake
      # - git
      # - pkg-config
      # - ... другие зависимости сборки Fooyin ...
      # Зависимости для сборки Qt и FFmpeg (если сборка происходит здесь)
      # - libgl1-mesa-dev
      # - libxcb1-dev
      # - libx11-dev
      # - ... другие зависимости Qt/FFmpeg ...
    exclude:
      # Явно исключаем стандартные версии Qt и FFmpeg
      - 'libqt6*'
      - 'qt6-*'
      - 'libavcodec*'
      - 'libavformat*'
      - 'libavutil*'
      - 'libswresample*'
      - 'libswscale*'
      # Исключаем старую версию ICU
      - 'libicu70'
      # Исключаем dev/dbg пакеты
      - '*-dev'
      - '*-dbg'
      - '*-doc'

  files:
    # Этот раздел описывает файлы, которые уже находятся в AppDir
    # и должны быть включены в финальный образ.
    # Эти файлы должны быть скопированы туда на предыдущих шагах workflow.
    include:
      # Исполняемый файл Fooyin (должен быть скопирован в AppDir/usr/local/bin)
      - usr/local/bin/fooyin
      # Десктоп-файл (должен быть создан и скопирован)
      - usr/local/share/applications/fooyin.desktop
      # Иконка (должна быть скопирована)
      - usr/local/share/icons/hicolor/*/apps/fooyin.png

      # Библиотеки Qt 6.8.0 (должны быть скопированы в AppDir/usr/local/lib)
      - usr/local/lib/libQt6*.so.*
      - usr/local/lib/x86_64-linux-gnu/libQt6*.so.*
      # Плагины Qt
      - usr/local/lib/x86_64-linux-gnu/qt6/plugins/**/*
      # QML
      - usr/local/lib/x86_64-linux-gnu/qt6/qml/**/*
      # Переводы Qt (опционально)
      # - usr/local/share/qt6/translations/**/*

      # Библиотеки FFmpeg 7.x (должны быть скопированы в AppDir/usr/local/lib)
      - usr/local/lib/libav*.so.*
      - usr/local/lib/libsw*.so.*

      # Библиотеки ICU 76 (должны быть скопированы в AppDir/usr/local/lib)
      - usr/local/lib/libicu*.so.*

    exclude:
      - usr/share/doc
      - usr/share/man
      - usr/local/share/doc
      - usr/local/share/man
      # Исключаем символические ссылки .so без версии, если они не нужны напрямую
      # appimage-builder обычно сам обрабатывает их копирование при необходимости.
      # - usr/local/lib/*.so

AppImage:
  arch: x86_64
  update-information: "gh-releases-zsync|fooyin/fooyin|latest|Fooyin-*-x86_64.AppImage.zsync"
