version: 1

AppDir:
  path: ./AppDir
  
  app_info:
    id: org.fooyin.Fooyin
    name: Fooyin
    icon: fooyin
    version: "@@VERSION@@"
    exec: bin/fooyin
    exec_args: $@

  runtime:
    env:
      LD_LIBRARY_PATH: ${APPDIR}/usr/local/lib:${APPDIR}/usr/local/lib/x86_64-linux-gnu:${APPDIR}/usr/lib/x86_64-linux-gnu:${APPDIR}/lib:${APPDIR}/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}
      QT_PLUGIN_PATH: ${APPDIR}/usr/local/lib/qt6/plugins:${APPDIR}/usr/local/lib/x86_64-linux-gnu/qt6/plugins:${APPDIR}/lib/qt6/plugins:${APPDIR}/lib/x86_64-linux-gnu/qt6/plugins
      QML2_IMPORT_PATH: ${APPDIR}/usr/local/lib/qt6/qml:${APPDIR}/usr/local/lib/x86_64-linux-gnu/qt6/qml:${APPDIR}/lib/qt6/qml:${APPDIR}/lib/x86_64-linux-gnu/qt6/qml

  apt:
    arch: amd64
    allow_unauthenticated: true
    sources:
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ jammy main universe'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x871920D1991BC93C'
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ jammy-updates main universe'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x871920D1991BC93C'
    include:
      - libpulse0
      - libasound2
      - libtag1v5
      - libglib2.0-0
      - zlib1g
      - libstdc++6
      - libxcb-cursor0
      - libxcb-randr0
      - libxcb-xfixes0
    exclude:
      - libqt6*
      - qt6-*
      - libavcodec*
      - libavformat*
      - libavutil*
      - libswresample*
      - libswscale*
      - libicu70
      - '*-dev'
      - '*-dbg'
      - '*-doc'

  files:
    include:
      # Основные файлы Fooyin
      - bin/fooyin
      - share/applications/fooyin.desktop
      - share/icons/hicolor/*/apps/fooyin.png

      # Qt 6.8.0 библиотеки
      - usr/local/lib/libQt6*.so.*
      - usr/local/lib/x86_64-linux-gnu/libQt6*.so.*
      - lib/libQt6*.so.*
      - lib/x86_64-linux-gnu/libQt6*.so.*

      # Qt плагины
      - usr/local/lib/qt6/plugins/**/*
      - usr/local/lib/x86_64-linux-gnu/qt6/plugins/**/*
      - lib/qt6/plugins/**/*
      - lib/x86_64-linux-gnu/qt6/plugins/**/*

      # Qt QML
      - usr/local/lib/qt6/qml/**/*
      - usr/local/lib/x86_64-linux-gnu/qt6/qml/**/*
      - lib/qt6/qml/**/*
      - lib/x86_64-linux-gnu/qt6/qml/**/*

      # FFmpeg 7.x
      - usr/local/lib/libav*.so.*
      - usr/local/lib/libsw*.so.*
      - lib/libav*.so.*
      - lib/libsw*.so.*

      # ICU 76
      - usr/local/lib/libicu*.so.*
      - lib/libicu*.so.*
    exclude:
      - '*.a'
      - '*.la'
      - '*.prl'
      - include/
      - 'cmake/'
      - 'pkgconfig/'
      - 'metatypes/'
      - 'phrasebooks/'
      - 'mkspecs/'

  test:
    skip: true

AppImage:
  arch: x86_64
  update-information: "gh-releases-zsync|fooyin/fooyin|latest|Fooyin-*-x86_64.AppImage.zsync"
  sign-key: none
