# .github/workflows/03-watch-fooyin-releases.yml
name: 03. Watch Fooyin Releases

on:
  schedule:
    # Проверять каждые 6 часов
    - cron: '0 */6 * * *'
  workflow_dispatch:

# --- Добавить это ---
permissions:
  actions: write # Для запуска других workflow
  contents: read  # По-прежнему нужно для listReleases

jobs:
  check-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest Fooyin release
        id: get-latest-release
        uses: actions/github-script@v7
        with:
          script: |
            const { data: releases } = await github.rest.repos.listReleases({
              owner: 'fooyin',
              repo: 'fooyin'
            });

            if (releases.length > 0) {
              const latestRelease = releases[0];
              core.setOutput('tag_name', latestRelease.tag_name);
              core.setOutput('html_url', latestRelease.html_url);
              core.info(`Latest Fooyin release: ${latestRelease.tag_name}`);
            } else {
              core.setFailed('No releases found for fooyin/fooyin');
            }

      - name: Check if release AppImage already exists (simplified check)
        id: check-artifact
        run: |
          # Это упрощенная проверка. В реальности можно проверить
          # существование релиза в *этом* репозитории с определенным тегом.
          # Пока просто выводим информацию.
          echo "Would check for existing AppImage for tag: ${{ steps.get-latest-release.outputs.tag_name }}"
          echo "check_result=not_implemented" >> $GITHUB_OUTPUT

      - name: Trigger AppImage build
        if: steps.check-artifact.outputs.check_result != 'found'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '02-build-fooyin-appimage.yml',
              ref: 'main', // Или ветка, где находится workflow
              inputs: {
                fooyin_ref: '${{ steps.get-latest-release.outputs.tag_name }}'
              }
            });
            core.info(`Triggered build for Fooyin ${{ steps.get-latest-release.outputs.tag_name }}`);
